self:
{
  config,
  lib,
  pkgs,
  ...
}:

let
  inherit (lib)
    concatLists
    concatMapStringsSep
    concatStringsSep
    escapeShellArg
    literalExpression
    mapAttrsToList
    mkIf
    mkOption
    optional
    optionalString
    optionals
    types
    ;

  cfg = config.programs.doors;

  angleType = types.addCheck types.str (s: builtins.match "-?[0-9]*\\.?[0-9]+deg" s != null) // {
    description = "an angle like \"90deg\"";
  };

  header = "# Generated by Home Manager. Edit programs.doors.settings, not this file.";
  boolString = b: if b then "1" else "0";
  envLines = mapAttrsToList (
    n: v: "doorsctl env set ${escapeShellArg n} ${escapeShellArg v}"
  ) cfg.settings.env;
  outputLines = mapAttrsToList (
    name: _:
    "doorsctl output ${escapeShellArg name} -d ${
      concatMapStringsSep " " escapeShellArg cfg.settings.desktop.workspaces
    }"
  ) cfg.settings.outputs;
  outputSettingsLines = concatLists (
    mapAttrsToList (
      name: oc:
      optional (oc.enable != null)
        "doorsctl output ${escapeShellArg name} ${if oc.enable then "enable" else "disable"}"
      ++ optional (oc.mode != null) "doorsctl output ${escapeShellArg name} mode ${oc.mode}"
      ++
        optional (oc.position != null)
          "doorsctl output ${escapeShellArg name} position ${toString oc.position.x} ${toString oc.position.y}"
      ++ optional (oc.scale != null) "doorsctl output ${escapeShellArg name} scale ${toString oc.scale}"
      ++ optional (
        oc.transform != null
      ) "doorsctl output ${escapeShellArg name} transform ${oc.transform}"
      ++ optional (oc.dpms != null) "doorsctl output ${escapeShellArg name} dpms ${oc.dpms}"
      ++ optional (
        oc.adaptive-sync != null
      ) "doorsctl output ${escapeShellArg name} adaptive_sync ${oc.adaptive-sync}"
      ++ optional (
        oc.render-bit-depth != null
      ) "doorsctl output ${escapeShellArg name} render_bit_depth ${oc.render-bit-depth}"
      ++ optional (
        oc.color-profile != null
      ) "doorsctl output ${escapeShellArg name} color_profile ${oc.color-profile}"
      ++ optional (
        oc.color-profile-icc != null
      ) "doorsctl output ${escapeShellArg name} color_profile icc ${toString oc.color-profile-icc}"
      ++ optional (oc.hdr != null) "doorsctl output ${escapeShellArg name} hdr ${oc.hdr}"
      ++ optional (oc.tearing != null) "doorsctl output ${escapeShellArg name} tearing ${oc.tearing}"
      ++ optional (
        oc.max-render-time != null
      ) "doorsctl output ${escapeShellArg name} max_render_time ${toString oc.max-render-time}"
    ) cfg.settings.outputs
  );
  desktopLines = optional (
    cfg.settings.desktop.defaultLayout != null
  ) "doorsctl desktop --layout ${cfg.settings.desktop.defaultLayout} --all";
  borderLines =
    prefix: b:
    optionals (b.color != null) [ "doorsctl config ${prefix}_border_color ${toString b.color}" ]
    ++ optionals (b.gradient.primary.color != null) [
      "doorsctl config ${prefix}_border_gradient ${toString b.gradient.primary.color}${
        optionalString (b.gradient.primary.angle != null) " ${toString b.gradient.primary.angle}"
      }"
    ]
    ++ optionals (b.gradient.secondary.color != null) [
      "doorsctl config ${prefix}_border_gradient2 ${toString b.gradient.secondary.color}${
        optionalString (b.gradient.secondary.angle != null) " ${toString b.gradient.secondary.angle}"
      }"
    ]
    ++ optionals (b.gradient.lerp != null) [
      "doorsctl config ${prefix}_border_gradient_lerp ${toString b.gradient.lerp}"
    ];
  windowSettingsLines = concatLists (
    mapAttrsToList (
      _: oc:
      optionals (oc.border != null) [ "doorsctl config border_width ${toString oc.border}" ]
      ++ optionals (oc.gap != null) [ "doorsctl config window_gap ${toString oc.gap}" ]
      ++ optionals (oc.smart-gaps != null) [ "doorsctl config smart_gaps ${boolString oc.smart-gaps}" ]
      ++ optionals (oc.smart-borders != null) [
        "doorsctl config smart_borders ${boolString oc.smart-borders}"
      ]
      ++ optionals (oc.focus-wrapping != null) [
        "doorsctl config focus_wrapping ${boolString oc.focus-wrapping}"
      ]
      ++ optionals (oc.focus-on-activate != null) [
        "doorsctl config focus_on_activate ${toString oc.focus-on-activate}"
      ]
      ++ optionals (oc.decoration-mode != null) [
        "doorsctl config decoration_mode ${toString oc.decoration-mode}"
      ]
      ++ optionals (oc.padding.top != null) [ "doorsctl config top_padding ${toString oc.padding.top}" ]
      ++ optionals (oc.padding.right != null) [
        "doorsctl config right_padding ${toString oc.padding.right}"
      ]
      ++ optionals (oc.padding.bottom != null) [
        "doorsctl config bottom_padding ${toString oc.padding.bottom}"
      ]
      ++ optionals (oc.padding.left != null) [
        "doorsctl config left_padding ${toString oc.padding.left}"
      ]
      ++ optionals (oc.respect-tiled-min-size != null) [
        "doorsctl config respect_tiled_min_size ${boolString oc.respect-tiled-min-size}"
      ]
      ++ optionals (oc.borderless-singleton != null) [
        "doorsctl config borderless_singleton ${boolString oc.borderless-singleton}"
      ]
      ++ optionals (oc.presel-feedback-color != null) [
        "doorsctl config presel_feedback_color ${oc.presel-feedback-color}"
      ]
      ++ optionals (oc.tiling-drag-indicator-color != null) [
        "doorsctl config tiling_drag_indicator_color ${oc.tiling-drag-indicator-color}"
      ]
      ++ borderLines "normal" oc.normal-border
      ++ borderLines "active" oc.active-border
      ++ borderLines "focused" oc.focused-border
    ) cfg.settings.config.windows
  );
  pointerSettingsLines = concatLists (
    mapAttrsToList (
      _: oc:
      optionals (oc.focus-follows-pointer != null) [
        "doorsctl config focus_follows_pointer ${toString oc.focus-follows-pointer}"
      ]
      ++ optionals (oc.pointer-follows-focus != null) [
        "doorsctl config pointer_follows_focus ${boolString oc.pointer-follows-focus}"
      ]
      ++ optionals (oc.click-to-focus != null) [
        "doorsctl config click_to_focus ${boolString oc.click-to-focus}"
      ]
    ) cfg.settings.config.pointer
  );

  tabSettingsLines = concatLists (
    mapAttrsToList (
      _: oc:
      optionals (oc.hide-lone-tab != null) [
        "doorsctl config hide_lone_tab ${boolString oc.hide-lone-tab}"
      ]
      ++ optionals (oc.color.bar-background != null) [
        "doorsctl config tab_color_bar_bg ${escapeShellArg oc.color.bar-background}"
      ]
      ++ optionals (oc.color.background != null) [
        "doorsctl config tab_color_bg ${escapeShellArg oc.color.background}"
      ]
      ++ optionals (oc.color.active-background != null) [
        "doorsctl config tab_color_bg_active ${escapeShellArg oc.color.active-background}"
      ]
      ++ optionals (oc.color.seperator != null) [
        "doorsctl config tab_color_sep ${escapeShellArg oc.color.seperator}"
      ]
    ) cfg.settings.config.tabs
  );

  scrollerSettingsLines = concatLists (
    mapAttrsToList (
      _: oc:
      optionals (oc.edge-scroller-pointer-focus != null) [
        "doorsctl config edge_scroller_pointer_focus ${boolString oc.edge-scroller-pointer-focus}"
      ]
      ++ optionals (oc.scroller-default-proportion != null) [
        "doorsctl config scroller_default_proportion ${toString oc.scroller-default-proportion}"
      ]
      ++ optionals (oc.scroller-focus-center != null) [
        "doorsctl config scroller_focus_center ${boolString oc.scroller-focus-center}"
      ]
      ++ optionals (oc.scroller-prefer-center != null) [
        "doorsctl config scroller_prefer_center ${boolString oc.scroller-prefer-center}"
      ]
      ++ optionals (oc.scroller-prefer-overspread != null) [
        "doorsctl config scroller_prefer_overspread ${boolString oc.scroller-prefer-overspread}"
      ]
      ++ optionals (oc.scroller-structs != null) [
        "doorsctl config scroller_structs ${toString oc.scroller-structs}"
      ]
    ) cfg.settings.config.scroller
  );

  miscSettingsLines = concatLists (
    mapAttrsToList (
      _: oc:
      optionals (oc.allow-tearing != null) [
        "doorsctl config allow_tearing ${boolString oc.allow-tearing}"
      ]
      ++ optionals (oc.auto-float-dialogs != null) [
        "doorsctl config auto_float_dialogs ${boolString oc.auto-float-dialogs}"
      ]
      ++ optionals (oc.enable-minimize != null) [
        "doorsctl config enable_minimize ${boolString oc.enable-minimize}"
      ]
      ++ optionals (oc.minimize-to-scratchpad != null) [
        "doorsctl config minimize_to_scratchpad ${boolString oc.minimize-to-scratchpad}"
      ]
      ++ optionals (oc.directional-focus-tightness != null) [
        "doorsctl config directional_focus_tightness ${toString oc.directional-focus-tightness}"
      ]
      ++ optionals (oc.record-history != null) [
        "doorsctl config record_history ${boolString oc.record-history}"
      ]
      ++ optionals (oc.mapping-events-count != null) [
        "doorsctl config mapping_events_count ${toString oc.mapping-events-count}"
      ]
      ++ optionals (oc.ignore-ewmh-fullscreen != null) [
        "doorsctl config ignore_ewmh_fullscreen ${toString oc.ignore-ewmh-fullscreen}"
      ]
      ++ optionals (oc.split-ratio != null) [ "doorsctl config split_ratio ${toString oc.split-ratio}" ]
      ++ optionals (oc.automatic-scheme != null) [
        "doorsctl config automatic_scheme ${oc.automatic-scheme}"
      ]
      ++ optionals (oc.initial-polarity != null) [
        "doorsctl config initial_polarity ${oc.initial-polarity}"
      ]
    ) cfg.settings.config.misc
  );

  monocoleSettingsLines = concatLists (
    mapAttrsToList (
      _: oc:
      optionals (oc.borderless-monocle != null) [
        "doorsctl config borderless_monocle ${boolString oc.borderless-monocle}"
      ]
      ++ optionals (oc.gapless-monocle != null) [
        "doorsctl config gapless_monocle ${boolString oc.gapless-monocle}"
      ]
    ) cfg.settings.config.monocole
  );

  textSettingsLines = concatLists (
    mapAttrsToList (
      _: oc:
      optionals (oc.tab-color-text != null) [
        "doorsctl config tab_color_text ${escapeShellArg oc.tab-color-text}"
      ]
      ++ optionals (oc.tab-color-text-active != null) [
        "doorsctl config tab_color_text_active ${escapeShellArg oc.tab-color-text-active}"
      ]
      ++ optionals (oc.text-font != null) [ "doorsctl config text_font ${escapeShellArg oc.text-font}" ]
      ++ optionals (oc.text-height != null) [ "doorsctl config text_height ${toString oc.text-height}" ]
    ) cfg.settings.config.text
  );
in
{
  options = {
    programs.doors = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = ''
          Whether to enable Doors.
        '';
      };

      package = mkOption {
        type = types.package;
        default = self.packages.${pkgs.stdenv.hostPlatform.system}.doors;
        defaultText = literalExpression "self.packages.\${pkgs.stdenv.hostPlatform.system}.doors";
        description = ''
          The Doors package to use.
        '';
      };

      settings = mkOption {
        type = types.submodule {
          options = {
            outputs = mkOption {
              default = { };
              type = types.attrsOf (
                types.submodule {
                  options = {
                    enable = mkOption {
                      type = types.nullOr types.bool;
                      default = null;
                      example = true;
                      description = "Whether to enable this display, applied via doorsctl output <name> enable";
                    };

                    mode = mkOption {
                      type = types.nullOr types.str;
                      default = null;
                      example = "1920x1080@60.0";
                      description = "Resolution/Mode for this output, applied via doorsctl output <name> mode.";
                    };

                    position = mkOption {
                      type = types.nullOr (
                        types.submodule {
                          options = {
                            x = mkOption {
                              type = types.int;
                              default = 0;
                              defaultText = "0";
                              description = "X coordinate in pixels.";
                            };

                            y = mkOption {
                              type = types.int;
                              default = 0;
                              defaultText = "0";
                              description = "Y coordiate in pixels.";
                            };

                          };
                        }
                      );
                      default = null;
                      example = {
                        x = 0;
                        y = 0;
                      };
                      description = "Output position in layout.";
                    };

                    scale = mkOption {
                      type = types.nullOr types.number;
                      default = null;
                      example = 1.5;
                      description = "Scale factor for this output, applied via doorsctl output <name> scale.";
                    };

                    transform = mkOption {
                      type = types.nullOr (
                        types.enum [
                          "normal"
                          "90"
                          "180"
                          "270"
                          "flipped"
                          "flipped-90"
                          "flipped-270"
                        ]
                      );
                      default = null;
                      example = "90";
                      description = "Specify a rotation for this output. Prefix degrees with `flipped` to mirror the display";
                    };

                    dpms = mkOption {
                      type = types.nullOr (
                        types.enum [
                          "on"
                          "off"
                        ]
                      );
                      default = null;
                      example = "on";
                      description = "Set the state of `dpms` for this output.";
                    };

                    adaptive-sync = mkOption {
                      type = types.nullOr (
                        types.enum [
                          "on"
                          "off"
                        ]
                      );
                      default = null;
                      example = "on";
                      description = "Set the state of 'adaptive_sync' for this output.";
                    };

                    render-bit-depth = mkOption {
                      type = types.nullOr (
                        types.enum [
                          "8"
                          "10"
                        ]
                      );
                      default = null;
                      example = "8";
                      description = "Set the `render_bit_depth` of this output.";
                    };

                    color-profile = mkOption {
                      type = types.nullOr (
                        types.enum [
                          "gamma22"
                          "srgb"
                        ]
                      );
                      default = null;
                      example = "gamma22";
                      description = "Set the 'color_profile' of this output.";
                    };

                    color-profile-icc = mkOption {
                      type = types.nullOr types.path;
                      default = null;
                      example = "/path/to/profile.icc";
                      description = "Set the 'color_profile icc' of this output from a file.";
                    };

                    hdr = mkOption {
                      type = types.nullOr (
                        types.enum [
                          "on"
                          "off"
                        ]
                      );
                      default = null;
                      example = "on";
                      description = "Set the 'hdr' state for this output. (requires Vulkan renderer, PQ/BT.2020 display support)";
                    };

                    tearing = mkOption {
                      type = types.nullOr (
                        types.enum [
                          "on"
                          "off"
                        ]
                      );
                      default = null;
                      example = "on";
                      description = "Whether to allow tearing on this output.";
                    };

                    max-render-time = mkOption {
                      type = types.nullOr types.str;
                      default = null;
                      example = "1";
                      description = "Set the max rendering time for this output, measured in ms. Can also be set to `off`";
                    };

                  };
                }
              );
            };

            desktop = mkOption {
              type = types.submodule {
                options = {
                  defaultLayout = mkOption {
                    type = types.nullOr (
                      types.enum [
                        "tiled"
                        "monocle"
                        "scroller"
                        "master_stack"
                      ]
                    );
                    default = null;
                    example = "tiled";
                    description = "Default layout mode to be applied to ALL desktops. Layout will reset to this on every session restart if value is set.";
                  };

                  workspaces = mkOption {
                    type = types.listOf types.str;
                    default = [
                      "I"
                      "II"
                      "III"
                    ];
                    description = "Names of the desktops applied to each output. The number of desktops is determined by the number of names provided.";
                  };
                };
              };
              default = { };
              description = "Desktop setup applied by doors at startup: workspace names per output and an optional default layout for all desktops.";
            };

            config = mkOption {
              type = types.submodule {
                options = {
                  windows = mkOption {
                    default = { };
                    type = types.attrsOf (
                      types.submodule {
                        options = {
                          border = mkOption {
                            type = types.nullOr types.int;
                            default = null;
                            example = 2;
                            description = "Sets the border width around windows. Doors default: 2.";
                          };

                          gap = mkOption {
                            type = types.nullOr types.int;
                            default = null;
                            example = 10;
                            description = "Sets the gap between windows. Doors default: 10.";
                          };

                          smart-gaps = mkOption {
                            type = types.nullOr types.bool;
                            default = null;
                            description = "When true, window gaps are disabled when there is only one tiled window on the desktop.";
                          };

                          smart-borders = mkOption {
                            type = types.nullOr types.bool;
                            default = null;
                            description = "When true, window borders are hidden when there is only one tiled window on the desktop.";
                          };

                          focus-wrapping = mkOption {
                            type = types.nullOr types.bool;
                            default = null;
                            description = "When true, directional focus wraps around when there is no window in the target direction (e.g., focusing west from the leftmost window wraps to the rightmost).";
                          };

                          focus-on-activate = mkOption {
                            type = types.nullOr (
                              types.enum [
                                "focus"
                                "none"
                                "smart"
                                "urgent"
                              ]
                            );
                            default = null;
                            example = "focus";
                            description = ''
                              Controls what happens when a window request activation (new window mapping, XDG activation, `_NET_ACTIVE_WINDOW`, foreign toplevel requests.

                                                        focus (default): The requesting window recieves keyboard focus immediately.
                                                        none: Activation only updates the visual state (borders, tab highlights) without stealing keyboard focus.
                                                        smart: The window receives keyboard focus only if it is on the currently focused desktop. Otherwise only visual state is updated.
                                                        urgent: The window is marked as urgent (visual indicator) instead of receiving keyboard focus.'';
                          };

                          decoration-mode = mkOption {
                            type = types.nullOr (
                              types.enum [
                                "none"
                                "tabs"
                                "always"
                                "csd"
                              ]
                            );
                            default = null;
                            example = "always";
                            description = ''
                              Controls how window decorations (titlebars, borders) are displayed:

                              none: All windows render without decorations by signaling them to enter fullscreen mode. Tab bars are also hidden. Provides a clean, minimal interface.
                              tabs: Tab bars are shown in tabbed layouts, but clients are kept in fullscreen mode to hide client-side decorations. No CSD is visible anywhere.
                              always: Decorations are always visible. In tabbed layouts, server-side tab bars replace client decorations. Outside tabbed layouts, clients use their own CSD.
                              csd: Client-side decorations are always shown, even in tabbed layouts. Tab bars are hidden and every window draws it's own decorations.

                              Clients that do not support `xdg-decoration` keep their own client-side decorations in `none` and `tabs` modes.
                            '';
                          };

                          borderless-singleton = mkOption {
                            type = types.bool;
                            default = false;
                            description = "When true, removes borders from singleton windows";
                          };

                          padding = mkOption {
                            type = types.submodule {
                              options = {
                                top = mkOption {
                                  type = types.nullOr types.int;
                                  default = null;
                                  example = 0;
                                  description = "Sets the top padding (margin) for all desktops";
                                };
                                right = mkOption {
                                  type = types.nullOr types.int;
                                  default = null;
                                  example = 0;
                                  description = "Sets the right padding for all desktops";
                                };
                                bottom = mkOption {
                                  type = types.nullOr types.int;
                                  default = null;
                                  example = 0;
                                  description = "Sets the bottom padding for all desktops";
                                };
                                left = mkOption {
                                  type = types.nullOr types.int;
                                  default = null;
                                  example = 0;
                                  description = "Sets the left padding for all desktops";
                                };
                              };
                            };
                          };

                          respect-tiled-min-size = mkOption {
                            type = types.nullOr types.bool;
                            default = null;
                            example = true;
                            description = "When true, tiled windows will not go below their configured minimum size no matter what.";
                          };

                          normal-border = mkOption {
                            type = types.submodule {
                              options = {
                                color = mkOption {
                                  type = types.nullOr types.str;
                                  default = null;
                                  example = "FFFFFF";
                                  description = "Sets the primary border color for unfocused/inactive windows";
                                };
                                gradient = mkOption {
                                  type = types.submodule {
                                    options = {
                                      primary = mkOption {
                                        type = types.submodule {
                                          options = {
                                            color = mkOption {
                                              type = types.nullOr types.str;
                                              default = null;
                                              example = "FFFFFF";
                                              description = "Sets the color of the primary gradient to be applied to `normal-border`.";
                                            };
                                            angle = mkOption {
                                              type = types.nullOr (types.strMatching "-?[0-9]*\\.?[0-9]+deg");
                                              default = null;
                                              example = "90deg";
                                              description = "Sets the angle of the primary gradient to be applied to `normal-border`.";
                                            };
                                          };
                                        };
                                        description = "Sets the values of the primary gradient to be applied to 'normal-border'.";
                                      };
                                      secondary = mkOption {
                                        type = types.submodule {
                                          options = {
                                            color = mkOption {
                                              type = types.nullOr types.str;
                                              default = null;
                                              example = "FFFFFF";
                                              description = "Sets the color of the secondary gradient to be applied to `normal-border`.";
                                            };
                                            angle = mkOption {
                                              type = types.nullOr (types.strMatching "-?[0-9]*\\.?[0-9]+deg");
                                              default = null;
                                              example = "90deg";
                                              description = "Sets the color of the secondary gradient to be applied to `normal-border`.";
                                            };
                                          };
                                        };
                                        description = "Sets the values of the secondary gradient to be applied to 'normal-border'. It blends with the primary gradient via the corresponding `lerp` setting.";
                                      };
                                      lerp = mkOption {
                                        type = types.nullOr (
                                          types.addCheck types.number (x: x >= 0.0 && x <= 1.0)
                                          // {
                                            description = "An option between 0.0 and 1.0";
                                          }
                                        );
                                        default = null;
                                        example = 0.5;
                                        description = "Controls the blend between the primary and secondary gradient. `0.0` only shows the primary gradient, `1.0` only shows the secondary. Linear interpolation is applied between the two.";
                                      };
                                    };
                                  };
                                };
                              };
                            };
                          };

                          active-border = mkOption {
                            type = types.submodule {
                              options = {
                                color = mkOption {
                                  type = types.nullOr types.str;
                                  default = null;
                                  example = "FFFFFF";
                                  description = "Sets the primary border color for unfocused/inactive windows";
                                };
                                gradient = mkOption {
                                  type = types.submodule {
                                    options = {
                                      primary = mkOption {
                                        type = types.submodule {
                                          options = {
                                            color = mkOption {
                                              type = types.nullOr types.str;
                                              default = null;
                                              example = "FFFFFF";
                                              description = "Sets the color of the primary gradient to be applied to `active-border`.";
                                            };
                                            angle = mkOption {
                                              type = types.nullOr (types.strMatching "-?[0-9]*\\.?[0-9]+deg");
                                              default = null;
                                              example = "90deg";
                                              description = "Sets the angle of the primary gradient to be applied to `active-border`.";
                                            };
                                          };
                                        };
                                        description = "Sets the values of the primary gradient to be applied to 'active-border'.";
                                      };
                                      secondary = mkOption {
                                        type = types.submodule {
                                          options = {
                                            color = mkOption {
                                              type = types.nullOr types.str;
                                              default = null;
                                              example = "FFFFFF";
                                              description = "Sets the color of the secondary gradient to be applied to `active-border`.";
                                            };
                                            angle = mkOption {
                                              type = types.nullOr (types.strMatching "-?[0-9]*\\.?[0-9]+deg");
                                              default = null;
                                              example = "90deg";
                                              description = "Sets the color of the secondary gradient to be applied to `active-border`.";
                                            };
                                          };
                                        };
                                        description = "Sets the values of the secondary gradient to be applied to 'active-border'. It blends with the primary gradient via the corresponding `lerp` setting.";
                                      };
                                      lerp = mkOption {
                                        type = types.nullOr (
                                          types.addCheck types.number (x: x >= 0.0 && x <= 1.0)
                                          // {
                                            description = "An option between 0.0 and 1.0";
                                          }
                                        );
                                        default = null;
                                        example = 0.5;
                                        description = "Controls the blend between the primary and secondary gradient. `0.0` only shows the primary gradient, `1.0` only shows the secondary. Linear interpolation is applied between the two.";
                                      };
                                    };
                                  };
                                };
                              };
                            };
                          };

                          focused-border = mkOption {
                            type = types.submodule {
                              options = {
                                color = mkOption {
                                  type = types.nullOr types.str;
                                  default = null;
                                  example = "FFFFFF";
                                  description = "Sets the primary border color for unfocused/inactive windows";
                                };
                                gradient = mkOption {
                                  type = types.submodule {
                                    options = {
                                      primary = mkOption {
                                        type = types.submodule {
                                          options = {
                                            color = mkOption {
                                              type = types.nullOr types.str;
                                              default = null;
                                              example = "FFFFFF";
                                              description = "Sets the color of the primary gradient to be applied to `normal-border`.";
                                            };
                                            angle = mkOption {
                                              type = types.nullOr (types.strMatching "-?[0-9]*\\.?[0-9]+deg");
                                              default = null;
                                              example = "90deg";
                                              description = "Sets the angle of the primary gradient to be applied to `normal-border`.";
                                            };
                                          };
                                        };
                                        description = "Sets the values of the primary gradient to be applied to 'normal-border'.";
                                      };
                                      secondary = mkOption {
                                        type = types.submodule {
                                          options = {
                                            color = mkOption {
                                              type = types.nullOr types.str;
                                              default = null;
                                              example = "FFFFFF";
                                              description = "Sets the color of the secondary gradient to be applied to `focused-border`.";
                                            };
                                            angle = mkOption {
                                              type = types.nullOr (types.strMatching "-?[0-9]*\\.?[0-9]+deg");
                                              default = null;
                                              example = "90deg";
                                              description = "Sets the color of the secondary gradient to be applied to `focused-border`.";
                                            };
                                          };
                                        };
                                        description = "Sets the values of the secondary gradient to be applied to 'focused-border'. It blends with the primary gradient via the corresponding `lerp` setting.";
                                      };
                                      lerp = mkOption {
                                        type = types.nullOr (
                                          types.addCheck types.number (x: x >= 0.0 && x <= 1.0)
                                          // {
                                            description = "An option between 0.0 and 1.0";
                                          }
                                        );
                                        default = null;
                                        example = 0.5;
                                        description = "Controls the blend between the primary and secondary gradient. `0.0` only shows the primary gradient, `1.0` only shows the secondary. Linear interpolation is applied between the two.";
                                      };
                                    };
                                  };
                                };
                              };
                            };
                          };

                          presel-feedback-color = mkOption {
                            type = types.nullOr types.str;
                            default = null;
                            example = "FFFFFF";
                            description = "Sets the color of the preselection feedback indicator.";
                          };

                          tiling-drag-indicator-color = mkOption {
                            type = types.nullOr types.str;
                            default = "4d9eff4d";
                            example = "FFFFFF";
                            description = "Sets the color of the tiling drag overlay indicator (default: 4d9eff4d)";
                          };

                        };
                      }
                    );
                    description = "Options relating to session windows.";
                  };

                  text = mkOption {
                    default = { };
                    type = types.attrsOf (
                      types.submodule {
                        options = {
                          tab-color-text = mkOption {
                            type = types.nullOr types.str;
                            default = null;
                            example = "255 255 255 1.0";
                            description = "Sets the color of tab text.";
                          };

                          tab-color-text-active = mkOption {
                            type = types.nullOr types.str;
                            default = null;
                            example = "255 255 255 1.0";
                            description = "Sets the color of active tab text.";
                          };

                          text-font = mkOption {
                            type = types.nullOr types.str;
                            default = null;
                            example = "JetBrainsMono Nerd Font";
                            description = "Sets the font used for tab text.";
                          };

                          text-height = mkOption {
                            type = types.nullOr types.int;
                            default = null;
                            example = 12;
                            description = "Sets the height of tab text.";
                          };
                        };
                      }
                    );
                    description = "Options relating to 'text'.";
                  };

                  pointer = mkOption {
                    default = { };
                    type = types.attrsOf (
                      types.submodule {
                        options = {
                          focus-follows-pointer = mkOption {
                            type = types.nullOr (
                              types.enum [
                                "no"
                                "yes"
                                "always"
                              ]
                            );
                            default = "no";
                            description = ''
                              Controls whether keyboard focus follows the pointer cursor.

                                no (default): Focus never follows the pointer.
                                yes: Focus follows the pointer when moving over a window.
                                always: Same as `yes`, but also clears keyboard focus when the pointer moves to the background or over non-window surfaces (e.g., bars, notifications).
                            '';
                          };

                          pointer-follows-focus = mkOption {
                            type = types.bool;
                            default = false;
                            description = "When true, the pointer is warped to follow window focus changes.";
                          };

                          click-to-focus = mkOption {
                            type = types.bool;
                            default = false;
                            description = "When true, clicking a window focuses it.";
                          };
                        };
                      }
                    );
                    description = "Options relating to the 'pointer'.";
                  };

                  tabs = mkOption {
                    default = { };
                    type = types.attrsOf (
                      types.submodule {
                        options = {
                          hide-lone-tab = mkOption {
                            type = types.bool;
                            default = false;
                            description = "When true, the tab bar is hidden when a tabbed container has only one window.";
                          };

                          color = mkOption {
                            type = types.submodule {
                              options = {
                                bar-background = mkOption {
                                  type = types.nullOr types.str;
                                  default = null;
                                  example = "255 255 255 1.0";
                                  description = "Sets tab bar background color for tabbed layout. Uses RGBA color format.";
                                };

                                background = mkOption {
                                  type = types.nullOr types.str;
                                  default = null;
                                  example = "255 255 255 1.0";
                                  description = "Sets inactive tab background color. Uses RGBA color format.";
                                };

                                active-background = mkOption {
                                  type = types.nullOr types.str;
                                  default = null;
                                  example = "255 255 255 1.0";
                                  description = "Sets active tab background color. Uses RGBA color format.";
                                };

                                seperator = mkOption {
                                  type = types.nullOr types.str;
                                  default = null;
                                  example = "255 255 255 1.0";
                                  description = "Sets tab separator color. Uses RGBA color format.";
                                };
                              };
                            };
                          };

                        };
                      }
                    );
                    description = "Options relating to 'tabs'.";
                  };

                  monocole = mkOption {
                    type = types.attrsOf (
                      types.submodule {
                        options = {
                          borderless-monocle = mkOption {
                            type = types.bool;
                            default = false;
                            description = "When true, removes borders in monocle layout.";
                          };

                          gapless-monocle = mkOption {
                            type = types.bool;
                            default = false;
                            description = "When true, windows are rearranged to fill gaps when windows are closed.";
                          };

                        };
                      }
                    );
                    description = "Options relating to the 'monocole'.";
                  };

                  scroller = mkOption {
                    type = types.attrsOf (
                      types.submodule {
                        options = {
                          edge-scroller-pointer-focus = mkOption {
                            type = types.nullOr types.bool;
                            default = null;
                            description = "When true, pointer focus affects scroller behavior at edges.";
                          };

                          scroller-default-proportion = mkOption {
                            type = types.nullOr (
                              types.addCheck types.number (x: x >= 0.1 && x <= 1.0)
                              // {
                                description = "An option between 0.0 and 1.0";
                              }
                            );
                            default = null;
                            example = 1.0;
                            description = "Sets the default proportion for scroller layout (0.1-1.0)";
                          };

                          scroller-focus-center = mkOption {
                            type = types.nullOr types.bool;
                            default = null;
                            description = "When true, the focused window is centered in the scroller viewpoint.";
                          };

                          scroller-prefer-center = mkOption {
                            type = types.nullOr types.bool;
                            default = null;
                            description = "When true, scroller layout prefers centering the focused window.";
                          };

                          scroller-prefer-overspread = mkOption {
                            type = types.nullOr types.bool;
                            default = null;
                            description = "When true, scroller layout prefers spreading windows to fill available space.";
                          };

                          scroller-structs = mkOption {
                            type = types.nullOr (
                              types.addCheck types.number (x: x >= 0.0) // { description = "A non-negative integer"; }
                            );
                            default = null;
                            description = "Sets the number of visible scroller structs (non-negative integer).";
                          };

                        };
                      }
                    );
                    description = "Options relating to the 'scroller'";
                  };

                  misc = mkOption {
                    type = types.attrsOf (
                      types.submodule {
                        options = {
                          allow-tearing = mkOption {
                            type = types.bool;
                            default = false;
                            description = "When true, windows may use tearing page flips (screen tearing) for lower latency. This allows the compositor to bypass vertical sync for eligible windows. Can be overridden per-window via window rules (define in extraConfig).";
                          };

                          auto-float-dialogs = mkOption {
                            type = types.bool;
                            default = false;
                            description = "When true, windows that advertise themselves as dialogs via the `xdg-dialog-v1` procotol are automatically floated when they open. This applies to both modal and non-modal dialogs. Window rules with an explicit `state` still take priority.";
                          };

                          enable-minimize = mkOption {
                            type = types.bool;
                            default = true;
                            description = "When false, minimizing is disabled entirely: the minimize capability is no longer advertised to clients, minimize requests from clients are ignored, and the minimize commands do nothing. Restoring already minimized windows keeps working.";
                          };

                          minimize-to-scratchpad = mkOption {
                            type = types.bool;
                            default = false;
                            description = "When true, minimizing a window sends it to the scratchpad instead of just hiding it. Minimized windows are then restored wither with `doorsctl scratchpad show` or with `doorsctl toggle restore_minimized`";
                          };

                          directional-focus-tightness = mkOption {
                            type = types.nullOr (
                              types.addCheck types.number (x: x >= 0 && x <= 100)
                              // {
                                description = "An option between 0 and 100";
                              }
                            );
                            default = null;
                            description = "Sets how tightly directional focus navigation favors close windows. 0=least strict, 100=most strict.";
                          };

                          record-history = mkOption {
                            type = types.bool;
                            default = true;
                            description = "When true, focus history is recorded for cycling through previous windows.";
                          };

                          mapping-events-count = mkOption {
                            type = types.nullOr (
                              types.addCheck types.number (x: x >= 0) // { description = "A non negative integer"; }
                            );
                            default = null;
                            description = "Sets the number of recent mapping events to track (non-negative integer)";
                          };

                          ignore-ewmh-fullscreen = mkOption {
                            type = types.nullOr (
                              types.addCheck types.number (x: x >= 0 && x <= 2)
                              // {
                                description = "An integer between and including 0-2";
                              }
                            );
                            default = null;
                            description = ''
                              Controls how EWMH fullscreen requests are handled:

                              0 = honor
                              1 = ignore
                              2 = auto
                            '';
                          };

                          split-ratio = mkOption {
                            type = types.nullOr (
                              types.addCheck types.number (x: x >= 0 && x <= 1)
                              // {
                                description = "Avalue between and including 0-1.0";
                              }
                            );
                            default = null;
                            example = 1.0;
                            description = "Sets the default split ration for new containers (0.0-1.0)";
                          };

                          automatic-scheme = mkOption {
                            type = types.nullOr (
                              types.enum [
                                "longest_side"
                                "alternate"
                                "spiral"
                              ]
                            );
                            default = null;
                            description = ''
                              Sets the automatic tiling scheme:

                              `longest_side`: Splits the largest container
                              `alternate`: Alternates direction
                              `spiral`: Spirals.
                            '';
                          };

                          initial-polarity = mkOption {
                            type = types.nullOr (
                              types.enum [
                                "first_child"
                                "second_child"
                              ]
                            );
                            default = null;
                            description = ''
                              Sets the initial insertion side for new windows:

                              `first_child`: Left/Top
                              `second_child`: Right/Bottom
                            '';
                          };

                        };
                      }
                    );
                    description = "Misc options.";
                  };

                };
              };
              default = { };
              description = ''
                Options to be applied under 'config' via 'doorsctl config'.
              '';
            };

            env = mkOption {
              type = types.attrsOf types.str;
              default = { };
              example = {
                XCURSOR_SIZE = "24";
                QT_QPA_PLATFORM = "wayland;xcb";
              };
              description = "Environment variables inherited by applications launched within 'Doors' (doorsctl env set).";
            };

            keybinds = mkOption {
              type = types.lines;
              default = "";
              description = "Keybinds to be passed to `doors/doorshkrc`. References for configuration can be found here: https://dawn.wine/CreeperFace/doors/src/branch/master/examples/doorshkrc";
            };

            extraConfig = mkOption {
              type = types.lines;
              default = "";
              description = "Extra configuration lines to be applied to the bottom of the configuration shell";
            };
          };
        };
        default = { };
        description = ''
          Settings available for configuring the 'Doors' environment. Applied to 'doorsrc'
        '';
      };
    };
  };

  config = mkIf cfg.enable {
    home.packages = [ cfg.package ];
    xdg.configFile."doors/doorsrc".text = concatStringsSep "\n" (
      [ header ]
      ++ envLines
      ++ outputLines
      ++ outputSettingsLines
      ++ desktopLines
      ++ windowSettingsLines
      ++ monocoleSettingsLines
      ++ pointerSettingsLines
      ++ tabSettingsLines
      ++ textSettingsLines
      ++ scrollerSettingsLines
      ++ miscSettingsLines
      ++ [ cfg.settings.extraConfig ]
    );

    xdg.configFile."doors/doorshkrc".text = concatStringsSep "\n" (
      [ header ] ++ [ cfg.settings.keybinds ]
    );
  };
}
