#! /bin/sh

# Example bwmrc configuration
# This file is executed at server startup

# Set up desktops on HDMI-A-1 (names separated by spaces)
bmsg output HDMI-A-1 -d I II III IV V VI VII VIII IX X

# Set border width
bmsg config border_width 2

# Set window gap
bmsg config window_gap 12

# Set single monocle
bmsg config single_monocle true

# Set borderless monocle
bmsg config borderless_monocle true

# Set gapless monocle
bmsg config gapless_monocle true

# Enable animations
bmsg config enable_animations true
